if only one package exists, use that one
Signed-off-by: Justin Lecher <jlec@gentoo.org>

diff --git a/app-admin/admin-tools/regen-meta-flat b/app-admin/admin-tools/regen-meta-flat
--- a/app-admin/admin-tools/regen-meta-flat
+++ b/app-admin/admin-tools/regen-meta-flat
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-source /etc/make.conf
+if [[ -e /etc/portage/make.conf ]]; then
+	source /etc/portage/make.conf
+elif [[ -e /etc/make.conf ]]; then
+	source /etc/make.conf
+else
+	echo "Cannot find make.conf"
+	exit 1
+fi
 
 NUMPROC=$(nproc)
 
